title: "SCRIPT Tutorials"
baseURL: "https://lcharleux.github.io/SIE_SCRIPT_tutorial/"

defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableGitInfo: true
enableRobotsTXT: true
removePathAccents: true
summaryLength: 30

ignoreFiles:
  - "\\.ipynb$"
  - "\\.ipynb_checkpoints$"
  - "\\.Rmd$"
  - "\\.Rmarkdown$"
  - "_cache$"
  - "content/(authors|courses|event|post)/.*"

outputs:
  home:
    - HTML
    - RSS
    - JSON
  section:
    - HTML
    - RSS

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    lineNos: false
    style: github

imaging:
  resampleFilter: Lanczos
  quality: 90
  anchor: Smart

# taxonomies:
#   tag: tags
#   category: categories
