description: "Course notes and practical tutorials for reproducible scientific computing."
copyright: "L. Charleux and C. Elmo"

github_repo: "https://github.com/lcharleux/SIE_SCRIPT_tutorial"

ui:
  breadcrumb_disable: false
  footer_about_enable: false
  navbar_logo: false
  sidebar_menu_compact: false
  sidebar_search_disable: false
  sidebar_menu_foldable: true
  showLightDarkModeMenu: true

links:
  user:
    - name: "USMB"
      url: "https://www.univ-smb.fr/"
      icon: "fa-solid fa-building-columns"
      desc: "Université Savoie Mont Blanc"
  developer:
    - name: "GitHub"
      url: "https://github.com/lcharleux/SIE_SCRIPT_tutorial"
      icon: "fab fa-github"
      desc: "Source repository"

offlineSearch: true
